# Generated by Django 5.0.1 on 2024-01-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('carpets', 'CARPETS'), ('dress', 'DRESS'), ('tops', 'TOPS'), ('skirts', 'SKIRTS'), ('handbags', 'HANDBAGS')], max_length=24),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=24),
        ),
    ]
